### ISSUE TITLE
README

### ISSUE THREAD

**Issue by karoliskoncevicius** [moodymudskipper/rangeops#11]
README file is still missing. Should include all the operators and the rationale for each of them, as well as examples.

**Comment by moodymudskipper** [comment]
@KKPMW I've added a README, but I'm not very good at readmes :) . Can you take a look ?
I think the package should be pretty much done now, we should just make sure the doc of the functions is OK as I haven't looked at it for a long time.

**Comment by moodymudskipper** [comment]
https://github.com/moodymudskipper/rangeops/commit/de1e676554a6db4d35340337651c02bb51445dad

**Comment by karoliskoncevicius** [comment]
Thanks! Will look over the README and all other changes as well, and will see if I can add/improve anything. I am also not a good README writer (look at the READMEs for my packages here on github heh..) and on top of that - I have a mild fever currently. But want to contribute, so cloning the repo and looking over it now.

**Comment by karoliskoncevicius** [comment]
my suggested version in #24

**Comment by moodymudskipper** [comment]
Cool, I like your structure much more, and the table is a good idea. Did you put it in code for a reason, rather than displaying a markdown table?

**Comment by karoliskoncevicius** [comment]
I don't like the zebra stripes in GitHub table rendering. Also when you put normal text in one column but code in another it makes it look even weirder. When it's all in code the table is more "flat" looking. That's the only reason...

**Comment by moodymudskipper** [comment]
Alright, I'm not sure if it looks less weird to have a table in a code block but that's a detail either way. I think we can close this then

**Comment by karoliskoncevicius** [comment]
@moodymudskipper I think you are right - README seems to look better with normal tables here. If you want that version - it's in branch dev_readme now.
