### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/rangeops#15]
this deserves its own issue.

I don't have a lot of ideas so far, apart from the fact I don't like the current one :).

The package checks, replaces, subsets, etc, and it uses infix operators for all operations.

*infixer* wasn't a bad name.
*operators* is taken, *ops* is catchy but not very specific.

could be a less technical but more evocative name, a tool, an animal, a sound...

could be an acronym made from what it does, wouldn't be very evocative but would be short enough to remember easily.

**Comment by karoliskoncevicius** [comment]
We can use `infixer` if you like it more, I already deleted my old repo. Also we can sleep on it see if some name comes up :) `rangeops` is not that bad too, but the package is not really only about ranges.

`operators` would have been a real good fit...

**Comment by karoliskoncevicius** [comment]
A short list of some that came to mind:

- infixer (the one that was used before)
- rangeops (current one)
- intrix (read %in% tricks, similar to `plotrix` pacakge)
- inops (%in% like operators)

**Comment by moodymudskipper** [comment]
after almost a month I think I like `inops` :)

**Comment by moodymudskipper** [comment]
@KKPMW can we go for inops and close this ?

**Comment by karoliskoncevicius** [comment]
@moodymudskipper agree about `inops`. Will you also rename the github repo?

**Comment by moodymudskipper** [comment]
Yes I will, I think it should go smoothly

**Comment by moodymudskipper** [comment]
done with f366a1a933d6477c1659f92ce6901783b7a1f5fd and 8d190fca2b0e8677fb6282f19a05614ba2308670
