### ISSUE TITLE
CRAN issues

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/rangeops#38]
@KKPMW 

> Thanks,
> 
> If there are references describing the methods in your package, please
> add these in the description field of your DESCRIPTION file in the form
> authors (year) <doi:...>
> authors (year) <arXiv:...>
> authors (year, ISBN:...)
> or if those are not available: <https:...>
> with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
> auto-linking.
> 
> Please fix and resubmit, and document what was changed in the submission
> comments.
> 
> Best,
> Jelena Saf

**Comment by karoliskoncevicius** [comment]
What hm. Is this all? What if there are no references describing the methods?

**Comment by moodymudskipper** [comment]
I don't get it, this is chineses to me tbh, 5th to 7th bullet points here seem relevant : https://cran.r-project.org/web/packages/submission_checklist.html . But these are used for academic references aren't they ?

She says "If there are references describing the methods in your package", so I can resubmit without change saying there is no reference ?

Or this is relevant to us "or if those are not available: https:..."  ? But then I don't really get what's expected either

**Comment by karoliskoncevicius** [comment]
I am confused as well. We have a space after ":" in "Suggests: ". Maybe that tipped off some auto-checker? Let me go through the DESCRIPTION one more time.

**Comment by karoliskoncevicius** [comment]
I noticed "inops" was in "JS" folder after being rejected. Do you know someone who would know what that folder means?

**Comment by karoliskoncevicius** [comment]
Ah, I think I get it - we didn't add "URL:" part which could simply be a link to our github.

**Comment by moodymudskipper** [comment]
What do you mean it's in JS folder ?

These 2 didn't have an URL field and the Suggests field looks the same, but it was reviewed by Uwe, not Jelena: 

https://github.com/moodymudskipper/unglue/blob/master/DESCRIPTION
https://github.com/moodymudskipper/dotdot/blob/master/DESCRIPTION

**Comment by moodymudskipper** [comment]
oh, it must mean Jelena Saf :), and UL means Uwe Ligges,

I found this : https://cransays.itsalocke.com/articles/dashboard.html

**Comment by karoliskoncevicius** [comment]
Pushed the DESCRIPTION with URL and BugReports to master, Maybe we should simply re-submit and mention in the submission comment, that on the request of the reviewer we updated the DESCRIPTION file by adding URL and BugReports

**Comment by moodymudskipper** [comment]
resubmitted

**Comment by karoliskoncevicius** [comment]
The package got rejected again? What was the reason this time?

**Comment by moodymudskipper** [comment]
Has it? I haven't received any message yet

**Comment by karoliskoncevicius** [comment]
Ah, maybe no decision yet. I just saw that it is not in /newbies/ and not in /archive/ I now see it is in /JS/ again.

**Comment by karoliskoncevicius** [comment]
I think it is done: https://cran.r-project.org/web/packages/inops/index.html

**Comment by moodymudskipper** [comment]
Yes!

> Thanks,
> 
> on its way to CRAN.
> 
> Best,
> Jelena Saf

**Comment by karoliskoncevicius** [comment]
I pushed a "v0.0.1 " tag to "releases".

Should we add some kind of "CRAN" badge to readme?

**Comment by moodymudskipper** [comment]
Sure, I should do this to my other cran packages too, it didn't occur to me

**Comment by moodymudskipper** [comment]
I'll let you introduce it on reddit and I'll introduce it on twitter, possibly stealing your pitch if you do it first :)

**Comment by karoliskoncevicius** [comment]
Added badges for CRAN and Number of Dependencies.

With reddit it's a bit hit or miss. I think the timing of the post has a big effect. If you post it too early or too late or on the wrong day of the week, you might get little exposure.

**Comment by moodymudskipper** [comment]
Really? I thought anything interesting would reach the top 3 at some point. Well let's time it well then :).

**Comment by moodymudskipper** [comment]
One thing that we miss BTW is an hexagon logo. I'm not much of an designer and have no sketch in mind though :).

**Comment by karoliskoncevicius** [comment]
Maybe I am too old, but I don't really understand those hexagon stickers. I tried google'ing for info about what is the use for them, and wasn't able to get an answer. Do you know why people use them? Is it just a package "brand" quirk?

**Comment by karoliskoncevicius** [comment]
Done [HERE](https://www.reddit.com/r/rstats/comments/dynux4/introducing_new_package_inops_expansion_of_in/)

Hope I did not butcher the presentation too much. If you have suggestions - I can still edit the text.

**Comment by moodymudskipper** [comment]
Awesome, and the reactions are great! I'll introduce it on twitter tonight.
About the sticker, you got it about right, it's just a brand thing, and ultimately makes people take your package a little more seriously I suppose. It's also a visual aid, you associate the features with a logo, so you'll think of the package more easily when you need it.

**Comment by karoliskoncevicius** [comment]
I see. I am not against the sticker. But I have no experience designing one. And have no idea what would fit. Something clever would be nice thou ...

**Comment by moodymudskipper** [comment]
happily closing CRAN ISSUES :) (sticker ideas can go to a new thread when we get inspiration)
