### ISSUE TITLE
More fame and glory

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/rangeops#42]
I've bookmarked this thread a few months ago : https://twitter.com/dgkeyes/status/1164625536406212610

From it I made a rough checklist of what makes a package better or makes it look its best.
It can apply to any package and I'll probably use it for my other stuff, shoot if you have more ideas.

Maybe there are some things here that apply to inops :

**Package design :**

- [x] limit dependencies (better for regular users but also for reverse dependencies)
- [x] if dependencies are needed, strive to choose mainstream ones (users will be more familiar, and won't need to download them)
- [x] if dependencies are needed, strive to choose light ones (avoid dependencies with dependencies)
- [ ] Use mainstream testing workflow and  strive for 100% test coverage
- [ ] Have tests and code readable/understandable to users
- [ ] Test on different systems and different IDEs

**Documentation + online presence:**

- [x] Good file DESCRIPTION
- [x] Don't forget github description
- [x] Proper release
- [x] README
- [x] vignette(s)
- [x] use cases
- [ ] benchmarks
- [ ] pkgdown website / author website
- [ ] Have an attached peer reviewed publication
- [ ] document alternative choices to showcase why/when choosing our is appropriate
- [ ] Submit to CRAN task view https://cran.r-project.org/web/views/

**Advertising package (similar to "online" presence above, but with a timestamp):** 

- [ ] Introduce on R packages mailing list : https://stat.ethz.ch/mailman/listinfo/r-packages
- [ ] Submit post on https://rweekly.org/submit
- [ ] Submit post on r-bloggers.com
- [x] Twitter
- [x] Reddit
- [ ] RStudio Community
- [ ] submit to R journal https://journal.r-project.org/

**github Badges :** 

- [x] CRAN badge
- [ ] covr badge
- [ ] cranlogs badge
- [ ] travis badge

**Activity indicators :** 

- [ ] Push regularly enough to CRAN if improvements have been made (gives the best to users AND shows the package is still maintained)
- [ ] Prompt responses to bug reports and feature requests

**Things that are outside of our direct control :** 

- [ ] Author reputation/contributions
- [ ] github stars
- [ ] CRAN downloads
- [ ] reverse dependencies
- [ ] commit frequency (not technically outside our control, but not going to do it for no reason)

**Comment by karoliskoncevicius** [comment]
Thank you, good list. A lot of this we have already covered. And some of this we will not be able to cover - like a scientific publication.

>  Submit to CRAN task view https://cran.r-project.org/web/views/

I am not really sure how views work and if users can submit their packages to views. Seems like each view is curated by somebody.
