### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/rangeops#7]
to do

**Comment by karoliskoncevicius** [comment]
Will you want to use a package for testing, like `tinytests` or `testthat`?

**Comment by moodymudskipper** [comment]
I'm used to testthat, but whatever you're comfortable with works

**Comment by moodymudskipper** [comment]
started them to ensure that check operators are consistent between themselves and with equality / comparison ops when applied on different types/ classes

**Comment by moodymudskipper** [comment]
Using `covr::report()`, we're just at 27%, aiming for 100%

**Comment by moodymudskipper** [comment]
60% 👍

**Comment by moodymudskipper** [comment]
100% 👍
